name: fast_pw_manager
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.0.7
  toggle_switch: ^2.1.0
  bloc: ^8.1.2
  hydrated_bloc: ^9.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  path_provider: ^2.0.15
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  # timer_builder: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo/appLogo.png"
  min_sdk_android: 21 



flutter:


  uses-material-design: true

  
  assets:
    - assets/png_images/
    - assets/svg_images/
    - assets/app_logo/



 
 
